### PR TITLE
Change all the private properties to protected

### PR DESCRIPTION
**Pull request by fansaien**
The class extends this class can access the protected properties.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@fansaien can you provide an example of how you plan on extending this class that would require these to be protected instead of private?

**Comment by fansaien** [comment]
@LukeTowers 

Sure,

I would like to override the call() method to support PHP 5.6, just by removing the "string" keywords.
In addition, I need the array result of the response instead of the stdclass.

This call() function needs to access these properties.

**Comment by LukeTowers** [comment]
PHP 5.6 isn't going to work with this library whether or not you're overriding the call method, the type hints will still exist and PHP 5.6 won't know what to do with them. 

Also, I don't want to encourage the use of PHP 5.6.

As for the array result, you can simply typecast the object to an array with `(array) $shopify->call()` and that solves that issue.

**Comment by fansaien** [comment]
I override both __construct and call function, it is working on PHP 5.6 now.

The response is a multi-levels JSON result, the `(array) $shopify->call()` can not solve this problem.

The only way is to change the last line to `return json_decode($response->getBody(), true);`

**Comment by LukeTowers** [comment]
While I may make this change at some point in the future I don't agree with the provided use case of using on PHP 5.6 and I don't want to open myself up to having to support that case in the future so I'll be closing this PR. This library is simple enough that you can just copy it verbatim into your own project if that's what you need to do.

**Pull request closed without merging**
